### PR TITLE
updated readme as this(WoeUSB) is not really sold

### PR DESCRIPTION
**Pull request by smeierzubiesen**
added a strikethrough for the word 'sold' and replaced it with 'distributed'

### CODE REVIEW

**Comment by Lin-Buo-Ren** [comment]
I personally don't think that this change is necessary, user can download for gratis doesn't mean the "product" isn't sold.

Please explain you thought on this change more thoroughly, thanks.

**Comment by smeierzubiesen** [comment]
sorry, i suppose it's more of a accuracy thing for me, sold imho means that money changes hands in exchange for a service and/or goods. other than that there is probably no need to change this :) feel free to reject/close this branch/PR :)

**Comment by JonnyTech** [comment]
I agree with @smeierzubiesen that "sold" is not correct and should be replaced with "distributed" or "provided".

According to [dictionary.com](www.dictionary.com/browse/sold):

> sold: simple past tense and past participle of sell
> sell: to transfer (goods) to or render (services) for another in exchange for money; dispose of to a purchaser for a price: 

So you see, "sold" refers to money or a price.

In fact, the [gpl](https://www.gnu.org/licenses/gpl.txt) makes use of the word "distributed" in its text.

It may be trivial, but grammatically speaking the use of the word "sold" in this instance is technically incorrect.

**Comment by Lin-Buo-Ren** [comment]
According to git-blame the term usage is made by @slacka , have any thoughts?

**Comment by slacka** [comment]
This wording came from the original README which was written by a French native speaker. The meaning is clear, but if it bothers you, I'm fine with replacing sold with distributed, but there is no need for the `<strike>`.

**Comment by Lin-Buo-Ren** [comment]
https://www.gnu.org/philosophy/selling.html , just for info
I no longer object the change as I don't really care about this issue.

**Comment by slacka** [comment]
thanks for the patch

**Pull request merged**
