### PR TITLE
Explicitly use ntfs-3g (fixes #239)

### LINKED ISSUE #239: Explicitly use ntfs-3g
Using the latest version 3.2.12 from the master branch, `woeusb` aborted, because it couldn’t write to the target device. The problem is, that by default, `mount` uses the NTFS Linux kernel driver, only supporting read-only mode.

```
[263097.482279] sd 7:0:0:0: Attached scsi generic sg3 type 0
[263097.482432] sd 7:0:0:0: [sdc] 61282631 512-byte logical blocks: (31.4 GB/29.2 GiB)
[263097.482726] sd 7:0:0:0: [sdc] Write Protect is off
[263097.482727] sd 7:0:0:0: [sdc] Mode Sense: 53 00 00 08
[263097.482985] sd 7:0:0:0: [sdc] Write cache: disabled, read cache: enabled, doesn't support DPO or FUA
[263097.510904]  sdc: sdc1
[263097.511986] sd 7:0:0:0: [sdc] Attached SCSI removable disk
[263458.802581]  sdc:
[263458.832936]  sdc: sdc1
[263463.929685] ntfs: driver 2.1.32 [Flags: R/O MODULE].
```

Manually specifying `-t ntfs-3g` in the script `woeusb` made it work.

```
$ git diff
diff --git a/src/woeusb b/src/woeusb
index 3284259..82c3de4 100755
--- a/src/woeusb
+++ b/src/woeusb
@@ -32,6 +32,8 @@ set \
        -o nounset \
        -o pipefail
 
+set -x
+
 ## Enable aliases for easy access to functions
 shopt -s expand_aliases
 
@@ -1362,6 +1364,7 @@ mount_target_filesystem(){
 
        mount \
                --options "${mount_options}" \
+               -t ntfs-3g \
                "${target_partition}" \
                "${target_fs_mountpoint}" \
                || (
```

This is incompatible with FAT of course.

### PR DESCRIPTION
**Pull request by petabyteboy**

### CODE REVIEW

**Comment by petabyteboy** [comment]
I also noticed that mount -t ntfs-3g does not work on some distros, for example NixOS, so I would prefer to use the ntfs-3g binary directly.
And yes of course you are right, I will fix that.

**Comment by JonnyTech** [comment]
@petabyteboy I have made the suggested change in a fork, feel free to use it and add support for using ntfs-3g directly (I assume that you would replace `mount` with `mount.ntfs-3g` but am unable to test at present).

**Comment by JonnyTech** [comment]
EDIT: That should probably be `ntfs-3g` which on my system is located at `/bin/ntfs-3g`

**Comment by slacka** [comment]
Looks good. Thanks @petabyteboy

**Pull request merged**
